name: QuadWars
version: '${version}'
main: io.github.minus1over12.quadwars.QuadWars
api-version: '1.20.6'
author: War Pigeon
softdepend:
  - floodgate
permissions:
  quadwars.gamemaster:
    description: "Allows control of game state."
    default: op
  quadwars.player:
    description: "Allows the player to play the game."
    default: true
    children:
      quadwars.player.jointeam: true
  quadwars.player.jointeam:
    description: "Allows the player to join a team."
    default: true
commands:
  quadwars:
    description: "Shows info about the QuadWars plugin."
    usage: "/<command>"
    permission-message: "QuadWars made by War Pigeon"
  qwsetstate:
    description: "Sets the state of the game. You probably want to use /qwtransition instead."
    usage: "/<command> <state>"
    permission: quadwars.gamemaster
  jointeam:
    description: "Joins a team."
    usage: "/<command> <team>"
    permission: quadwars.player.jointeam
    permission-message: "You do not have permission to add yourself to a team."
  qwtransition:
    description: "Transitions the game to the next state, with an optional time delay."
    usage: "/<command> [<time>]"
    permission: quadwars.gamemaster
  worldborder:
    description: "An enhanced world border command that sets the world border across dimensions 
    with correct scaling."
    usage: |-
      /<command> add <distance> [<time>]
      /<command> set <distance> [<time>]
      /<command> damage (amount|buffer)
      /<command> get
      /<command> warning (distance|time)
    permission: quadwars.gamemaster
  qwgetstate:
    description: "Gets the current phase of the game."
    usage: "/<command>"
    permission: quadwars.gamemaster